# ===== common (local/prod 공통) =====
spring:
  application:
    name: NICHIYA

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: kr.co.bnk_marketproject_be.dto

  configuration:
    map-underscore-to-camel-case: false

server:
  port: 8080
  forward-headers-strategy: framework   # Spring Boot 2.6+ 권장
  servlet:
    context-path: /NICHIYA

# 어드민 로고 업로드 경로 (배포용 세현 수정)
app:
  upload:
    dir: upload

# ===== local =====
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: NICHIYA
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update            # 로컬 개발은 편하게 update
    open-in-view: false
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.mybatis: info
solapi:
  enabled: false           # 로컬에서 실제 문자 테스트할 거면 true
  # api.key/secret/number는 환경변수에서 주입 (없으면 빈 문자열)

# ===== prod (운영) =====
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:oracle:thin:@//43.200.69.114:1522/XEPDB1   # Service name 방식
    username: NICHIYA
    password: 1234         # 환경변수로 주입
  jpa:
    hibernate:
      ddl-auto: none              # ★ 스키마 올리기 전엔 none
    open-in-view: false
    properties:
      hibernate.format_sql: true

  # 구글 로그인 클라우드 콘솔 auth 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
            # redirect-uri는 기본값이 {baseUrl}/login/oauth2/code/{registrationId}
            # 필요하면 아래처럼 명시 가능:
            redirect-uri: "https://43-200-69-114.sslip.io/NICHIYA/login/oauth2/code/google"

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "https://43-200-69-114.sslip.io/NICHIYA/login/oauth2/code/kakao"
            scope: profile_nickname, account_email
            client-name: Kakao
            provider: kakao

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "https://43-200-69-114.sslip.io/NICHIYA/login/oauth2/code/naver"
            scope: name, email
            client-name: Naver
            provider: naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            required: true
            enable: true
          ssl:
            trust: smtp.gmail.com
# sms 인증 ( 모든API허용했기때문에 보안유지!!)
# Solapi 공통키 정의는 하지 않고, 프로필 별로 enabled 플래그만 사용
solapi:
  enabled: true    # 기본은 꺼둠(테스트 안전)
  api:
    key: ${SOLAPI_API_KEY:}
    secret: ${SOLAPI_API_SECRET:}
    number: ${SOLAPI_NUMBER:}
  mock: false # 통신사 인증 작동시 false로 하면 됨
app:
  upload:
    dir: upload
  #base-url: http://43.200.69.114:8080/NICHIYA

mybatis:
  configuration:
    map-underscore-to-camel-case: false
# =====test(CI)===========
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=Oracle;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

solapi:
  enabled: false
